name: Build APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install python3-pip openjdk-17-jdk unzip -y
          pip3 install buildozer cython

      - name: Install Android SDK and accept licenses
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip
          unzip commandlinetools-linux-11076708_latest.zip
          mkdir -p $HOME/android-sdk/cmdline-tools
          mv cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          yes | sdkmanager --licenses || true
          sdkmanager "build-tools;37.0.0" "platform-tools" "platforms;android-33"

      - name: Build APK
        run: |
          export ANDROID_HOME=$HOME/android-sdk
          export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: calc
          path: bin/*.apk
